LangString addOrReinstall ${LANG_SPANISH} "Agregar/Reinstalar componentes"
LangString alreadyInstalled ${LANG_SPANISH} "Ya esta instalado"
LangString alreadyInstalledLong ${LANG_SPANISH} "${PRODUCTNAME} ${VERSION} ya esta instalado. Selecciona la operacion que quieres realizar y haz clic en Siguiente para continuar."
LangString appRunning ${LANG_SPANISH} "{{product_name}} se esta ejecutando. Cierra la aplicacion e intentalo de nuevo."
LangString appRunningOkKill ${LANG_SPANISH} "{{product_name}} se esta ejecutando.$\nHaz clic en OK para cerrarla."
LangString chooseMaintenanceOption ${LANG_SPANISH} "Elige la opcion de mantenimiento."
LangString choowHowToInstall ${LANG_SPANISH} "Elige como quieres instalar ${PRODUCTNAME}."
LangString createDesktop ${LANG_SPANISH} "Crear acceso directo en el escritorio"
LangString dontUninstall ${LANG_SPANISH} "No desinstalar"
LangString dontUninstallDowngrade ${LANG_SPANISH} "No desinstalar (este instalador no permite bajar de version sin desinstalar)"
LangString failedToKillApp ${LANG_SPANISH} "No se pudo cerrar {{product_name}}. Cierra la aplicacion e intentalo de nuevo."
LangString installingWebview2 ${LANG_SPANISH} "Instalando WebView2..."
LangString newerVersionInstalled ${LANG_SPANISH} "Ya hay una version mas reciente de ${PRODUCTNAME} instalada. No se recomienda instalar una version anterior. Si deseas continuar, es mejor desinstalar la version actual primero. Selecciona la operacion y haz clic en Siguiente."
LangString older ${LANG_SPANISH} "anterior"
LangString olderOrUnknownVersionInstalled ${LANG_SPANISH} "Hay una version $R4 de ${PRODUCTNAME} instalada en el sistema. Se recomienda desinstalar la version actual antes de instalar. Selecciona la operacion y haz clic en Siguiente."
LangString silentDowngrades ${LANG_SPANISH} "Este instalador no permite bajar de version en modo silencioso. Usa la interfaz grafica del instalador.$\n"
LangString unableToUninstall ${LANG_SPANISH} "No se pudo desinstalar."
LangString uninstallApp ${LANG_SPANISH} "Desinstalar ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SPANISH} "Desinstalar antes de instalar"
LangString unknown ${LANG_SPANISH} "desconocida"
LangString webview2AbortError ${LANG_SPANISH} "No se pudo instalar WebView2. La aplicacion no puede ejecutarse sin WebView2. Reinicia el instalador."
LangString webview2DownloadError ${LANG_SPANISH} "Error: no se pudo descargar WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_SPANISH} "WebView2 se descargo correctamente"
LangString webview2Downloading ${LANG_SPANISH} "Descargando WebView2..."
LangString webview2InstallError ${LANG_SPANISH} "Error: la instalacion de WebView2 fallo con codigo $1"
LangString webview2InstallSuccess ${LANG_SPANISH} "WebView2 se instalo correctamente"
LangString deleteAppData ${LANG_SPANISH} "Eliminar datos de la aplicacion"
